### ISSUE TITLE
Blocking functions cause buffer to delay output

### ISSUE THREAD

**Issue by daegontaven** [daegontaven/AlphaHooks#5]
## Description
Blocking functions like `time.sleep()` cause output from `sys.stdout` to be appended to `console_log` when a loop is done executing.  This might be a problem with the buffer since disabling it works like a charm. But it is hard to be sure since it could also be a problem with blocking from the interpreter's side. This bug also prevents while loops from running at all.

## Step to reproduce bug
Running a for loop within the console of AlphaHooks.
```python
import time
for i in range(10):
    time.sleep(1)
    print(i)
 
```
The loop will wait a full 10 seconds. Then it will print() everything at once.
It has been tested to show that the prints() do execute. This can be observed in the stdout. The stdout stream that is being captured is added to a buffer and the buffer appends the stream to the console. The theory is that the events are not being processed until the loop exits. This also unusually coincides with the return of `InteractiveConsole.runcode(self, code)`.

**Comment by daegontaven** [comment]
Possible suspects:
https://github.com/daegontaven/AlphaHooks/blob/1d8419aaacba249c522fa035f47b4e69a774beb4/AlphaHooks/widgets/console/interpreters/python.py#L41

https://github.com/daegontaven/AlphaHooks/blob/1d8419aaacba249c522fa035f47b4e69a774beb4/AlphaHooks/widgets/console/stream.py#L39

**Comment by daegontaven** [comment]
## Possible Suspects:

https://github.com/daegontaven/AlphaHooks/blob/1d8419aaacba249c522fa035f47b4e69a774beb4/AlphaHooks/widgets/console/stream.py#L14-L40

https://github.com/daegontaven/AlphaHooks/blob/1d8419aaacba249c522fa035f47b4e69a774beb4/AlphaHooks/widgets/console/interpreters/python.py#L33-L44

**Note:**
This line blocks in the thread while running `result = InteractiveConsole.runcode(self, code) `.

**Comment by victortrac** [comment]
I have no idea what AlphaHooks is nor do I really know what you're trying to do. But how about just flushing the stdout buffer in your loop?

**Comment by Kielbiski** [comment]
Does using blahblahblah.flush() not work?

**Comment by daegontaven** [comment]
@victortrac @victortrac You're right flushing the buffer in the loop is pretty obvious if that code were running in the main loop. But it is running in an isolated(Thread) environment separated from the main thread. This is done so the GUI does not freeze while processing the loop. If you are not familiar with this part of the project, it is an embedded python interpreter. The loop runs in the interpreter and has no real influence over `sys.stdout`. But you guys may be right about the buffer not being flushed properly. Just have to rewrite `NewLineIO` so it can flush the buffer when a block size is reached.

**Comment by daegontaven** [comment]
This bug unfortunately cannot be solved without further slowing down development. Hence we'll have to settle for the original workaround QPlainTextEdit which has less features as opposed to QTextEdit. One of the issues with performance was with `send_console_log` doing auto scroll inefficiency.

https://github.com/daegontaven/AlphaHooks/blob/c8056159c2d92ac912a752aae9f534607392df99/AlphaHooks/widgets/console/display/python.py#L60-L78

**Comment by daegontaven** [comment]
Credit where it's due for the solution to this bug:
https://stackoverflow.com/a/46142888/5586359

**Comment by daegontaven** [comment]
This bug is reintroduced in https://github.com/daegontaven/AlphaHooks/commit/3d1832549110e961b51343b84849f05581a5f308. The difference is that the timer fails to timeout this time.
